### ISSUE TITLE
Move RMSF into pmda.rms

### ISSUE THREAD

**Issue by nawtrey** [MDAnalysis/pmda#103]
Need to create an rms module as in MDAnalysis.analysis.rms for RMSF. Instead of having pmda.rmsf all in one file, we will make a submodule:

`rms/__init__.py`
    `rmsd.py`
    `rmsf.py`

and `in __init__.py` we will have:

```python
from __future__ import absolute_import`
from .rmsf import RMSF
from .rmsd import RMSD

__all__ = ["RMSD", "RMSF"]
```

This will require doc restructuring.

**Comment by orbeckst** [comment]
@nawtrey do you think you could do the refactoring? This is the main thing that holds up 0.3.0 #106 .

**Comment by nawtrey** [comment]
Yes, I will make new PR here shortly.
