### ISSUE TITLE
broken  CI build when docs don't change

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/pmda#16]
### Expected behaviour

every submitted PR to master passes the unit tests (they are required for a merge)

### Actual behaviour

If we don't change the docs updating the website fails [travis log](https://travis-ci.org/MDAnalysis/pmda/jobs/287097848#L1912)

ping @orbeckst

**Comment by orbeckst** [comment]
Ok, sounds like a problem we had elsewhere. 

(This is hard to test on the first merge because the doc push only happens on successful merges...)

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by kain88-de** [comment]
I think we had this for mdanlaysis

**Comment by orbeckst** [comment]
Are you sure that this is due to the docs? https://travis-ci.org/MDAnalysis/pmda/jobs/287177464 has a cloudpickle failure, which might be a Python version problem... @mkhoshle does this look familiar?

**Comment by kain88-de** [comment]
please have a look into the log I linked against.

https://travis-ci.org/MDAnalysis/pmda/jobs/287097848#L1912

The other failure is because pmda does only work with mdanalysis develop branch.

**Comment by orbeckst** [comment]
Ok, thanks. I hadn't realized that you had a link in the original report.
