### ISSUE TITLE
create a 0.1.0 release

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/pmda#32]
The library is useful so we should release a 0.1.0.

- [x] GitHub
- [x] pypi
- [ ] conda 

@kain88-de do you have time to set up the conda infrastructure?

I'll register with zenodo so that we can also have a DOI, at least for right now.

**Comment by orbeckst** [comment]
@kain88-de I would cut a 0.1.0 from what we have. Anything else you think need to be done?

**Comment by orbeckst** [comment]
I want to change the "getting help" in README to point to the MDA user and developer list and use the issue tracker for reporting bugs. Ok?

**Comment by orbeckst** [comment]
I created a [0.1.0 rc1](https://github.com/MDAnalysis/pmda/releases/tag/0.1.0rc1) pre-release to trigger zenodo and added the zenodo badge together with a preliminary citation (as provided by http://doi.org/10.5281/zenodo.1244324).

**Comment by kain88-de** [comment]
I’m good with all you have done. I’m also happy making this a release.

**Comment by orbeckst** [comment]
0.1.0 released.

@kain88-de do you want to do a conda release, too, or leave it on pypi only for right now?

**Comment by kain88-de** [comment]
pip is fine for now.
