### ISSUE TITLE
online documentation

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/pmda#4]
You can copy the files from pytng or RotamerConvolve to get the simple standard layout and color scheme. (Perhaps we should have a repo just for the basic doc layout for easier cloning.)

It should appear as https://www.mdanalysis.org/pmda

**Comment by orbeckst** [comment]
If you need a logo placeholder... 

![pmda-logo](https://user-images.githubusercontent.com/237980/31473651-c75dfe80-aeaa-11e7-9ca4-545583593d2f.png)
[pmda-logo.pdf](https://github.com/MDAnalysis/pmda/files/1377598/pmda-logo.pdf)

**Comment by kain88-de** [comment]
@richardjgowers Do you mind settting up the travis doc build? With all the tokens and stuff?
