### ISSUE TITLE
parallel LeafletFinder

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/pmda#47]
Parallel version of the `MDAnalysis.analysis.leaflet.LeafletFinder` algorithm from @iparask (see upcoming paper https://arxiv.org/abs/1801.07630).

**Comment by iparask** [comment]
Hello @orbeckst ,

I see that the base class parallelizes over the frames a trajectory has. Our parallel implementation of the LeafletFinder parallelized the execution over a single frame. 

I will use the most effecient case based on what we did for the paper, but I may have to override the core functionality of the based class and parallelize for a single frame and create multiple Dask DAGs to execute over the frames. 

Is that something you think will be usefull or do you prefer to keep the core functionality as is?

**Comment by orbeckst** [comment]
The current framework might well be too limiting. I'm happy to consider other approaches!

It should present the same user interface but implementation details can differ. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
@iparask can you link to the code that you used for the paper?

**Comment by iparask** [comment]
Sorry for replying this late, but here is the code [link](https://github.com/radical-cybertools/midas/blob/master/leaflet_finder/Dask/LeafletFinderDaskParCC.py).

Please feel free to open tickets for discussion and any bugs that you may find if you want to run it.
