### ISSUE TITLE
Convenient test for different schedulers

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/pmda#57]
pmda can be used with different dask schedulers and in a single core variant. It would be nice if we have a pytest.fixture that is easy to use and runs a single test with all supported schedulers.

```python
from pmda.testing import scheduler

def test_custom(scheduler):
    a = AnalysisFromFunction(...).run(scheduler=scheduler)
```

I think it should be possible to parametrize over a fixture.

**Comment by orbeckst** [comment]
https://github.com/MDAnalysis/pmda/blob/2ff3db237b0bbe998cabe56b3e6d97466caf9d6e/pmda/test/test_parallel.py#L82

shows how to set-up a client with two workers as a session-scoped test fixture

**Comment by kain88-de** [comment]
https://docs.pytest.org/en/latest/fixture.html#fixture-parametrize

I thought of this. We can use it to generate multiple schedulers for different tests.

**Comment by orbeckst** [comment]
Yes, this is used in https://github.com/MDAnalysis/pmda/blob/2ff3db237b0bbe998cabe56b3e6d97466caf9d6e/pmda/test/test_parallel.py#L93
