### ISSUE TITLE
Add IO and computation time per block in timing

### ISSUE THREAD

**Issue by VOD555** [MDAnalysis/pmda#86]
### Expected behaviour
I/O and computation time per block should be stored in the timing object so that one can easily know the components of the total time used for each block.

### Actual behaviour
There are only I/o and computation time per frame saved in timing object.

### Currently version of MDAnalysis:
MDAnalysis 0.19.2
PMDA 0.2.1
dask 1.2.2

**Comment by orbeckst** [comment]
How about just storing the information for how to slice the per-frame times into blocks?
